
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[348] =
    {   0,
        0,    0,   56,   56,    0,    0,    0,    0,   71,   69,
       60,   61,   61,   29,   55,   68,   27,   69,   23,   33,
       15,   31,   17,   26,   69,   16,   62,   67,   35,   25,
       14,   19,   68,   68,   24,   34,   39,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   21,    1,   32,   56,   59,   59,
       58,   57,    7,    6,    6,    7,    4,    3,    3,   61,
       28,   68,   68,   13,   10,   36,   65,    0,    0,    5,
        2,   66,    0,    0,    0,   63,   63,    0,   37,   22,
       18,   20,   38,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,    9,   68,
       68,   68,   68,   68,   68,   68,   68,   45,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   30,   56,    0,
       59,   57,   56,    6,    8,    3,    0,   65,    0,    0,
       64,    0,   67,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,    9,   68,   68,
       68,   46,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,    0,   68,   68,   68,   64,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   44,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   12,   52,   68,   68,    0,   68,   68,   68,
       68,   68,   68,   41,   68,   68,   68,   68,   11,    9,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,    9,   68,   68,   53,    0,   68,
       51,    9,   68,   68,   68,   68,   43,   68,   68,   68,
       68,   68,   68,   68,   68,   49,   54,   50,   68,   68,

       68,   68,   42,    9,    0,   68,   40,   68,    9,   68,
       68,   68,   68,   68,   68,   68,   68,    0,    0,   68,
       68,   68,   68,   68,   68,    0,    0,   68,   68,   68,
        0,    0,   68,    0,    0,   68,    0,    0,    0,    0,
        0,    0,    0,    0,   48,   47,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   26,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   27,   24,   24,   24,   24,   24,   24,   24,
       28,   29,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   42,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    3,    1,    3,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    4,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[355] =
    {   0,
        0,    0,   58,   62,   66,   68,   70,   72,  320, 1085,
     1085, 1085,  313,  289, 1085,   63, 1085,  287, 1085, 1085,
     1085,  273, 1085,   62,   65,   76,   76,   80, 1085,   68,
      258,   80,   88,   92, 1085, 1085, 1085,   96,  101,  103,
      113,  107,  118,  122,  111,  149,  152,  156,  158,  105,
      160,  164,  162,  166, 1085,  216, 1085,  238, 1085,  262,
     1085,  186, 1085, 1085,  254,  231, 1085, 1085,  241, 1085,
     1085,  120,    0, 1085, 1085, 1085,  201,  199,  202, 1085,
     1085,  204,  224,  232,  234,  244,  252,  240, 1085, 1085,
     1085, 1085, 1085,  179,  236,  184,  272,  255,  260,  264,

      274,  209,  276,  280,  282,  284,  287,  294,  289,  300,
      304,  306,  310,  316,  318,  320,  324,  326,  328,  330,
      333,  340,  342,  345,  348,  352,  354,  359,  366,  368,
      376,  379,  384,  386,  388,  390,  396, 1085,  196,  410,
     1085, 1085,  192, 1085, 1085, 1085,  159,  404,  393,  400,
      428,  431,  439,  433,  424,  435,  450,  459,  461,  465,
      470,  476,  478,  480,  482,  486,  484,  490,  494,  496,
      504,  506,  508,  512,  516,  518,  523,  528,  536,  540,
      542,  544,  546,  549,  551,  553,  555,  558,  560,  570,
      579,  573,  582,  584,  587,  592,  594,  596,  599,  611,

      601,  607,  613,  162,  615,  617,  623,  632,  634,  628,
      637,  643,  640,  649,  651,  653,  655,  657,  663,  660,
      666,  669,  672,  674,  676,  679,  681,  684,  692,  699,
      701,  703,  705,  708,  711,  717,  719,  723,  725,  729,
      731,  733,  737,  745,  747,  749,  145,  752,  755,  757,
      759,  761,  763,  769,  772,  781,  785,  787,  789,  791,
      795,  797,  801,  808,  812,  814,  810,  819,  823,  825,
      832,  837,  841,  844,  846,  850,  854,  856,  150,  858,
      860,  864,  866,  868,  871,  879,  881,  884,  886,  890,
      893,  898,  900,  902,  906,  914,  917,  922,  925,  927,

      929,  931, 1085,  935,  141,  937,  940,  942,  946,  949,
      952,  958,  954,  962,  965,  967,  978,  138,  120,  980,
      982,  984,  986,  989,  998,  132,  110, 1000, 1005, 1007,
      107,  133, 1009,   97,   97, 1015,   96,   78,   92,   75,
       58,   54,   35,   28, 1085, 1085, 1085, 1064, 1068, 1072,
       63, 1076, 1080,   59
    } ;

static const flex_int16_t yy_def[355] =
    {   0,
      347,    1,  348,  348,  349,  349,  350,  350,  347,  347,
      347,  347,  347,  347,  347,  351,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  351,  351,  347,  347,  347,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  347,  347,  347,  352,  347,  347,
      347,  353,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  351,  354,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  351,  351,  351,  354,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  347,  352,  347,
      347,  347,  352,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  351,  351,  351,  354,  354,  354,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  347,  351,  351,  351,  354,  354,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  347,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  347,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  347,  351,  347,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  347,  347,  351,
      351,  351,  351,  351,  351,  347,  347,  351,  351,  351,
      347,  347,  351,  347,  347,  351,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,    0,  347,  347,  347,
      347,  347,  347,  347
    } ;

static const flex_int16_t yy_nxt[1146] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   16,   16,   33,   34,   35,   10,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   16,
       46,   16,   16,   47,   16,   48,   16,   49,   50,   51,
       52,   16,   53,   54,   16,   16,   16,   55,   56,   57,
       59,   60,   73,   61,   59,   60,   72,   61,   64,   65,
       64,   65,   68,   69,   68,   69,   75,   66,  346,   66,
       73,   73,   77,   77,   76,  345,   62,   80,   89,   90,
       62,   82,   81,   83,   83,   82,   78,   86,   87,  344,

       84,   92,   93,  343,   84,   73,   73,   85,   79,   73,
       73,   88,   84,   97,   97,  342,   84,  341,   73,   73,
       73,   73,   73,   73,   73,   73,  340,   98,   73,   73,
       73,   73,  339,   94,   99,   73,   73,   73,   73,   73,
       73,  128,   95,  108,  338,  104,  337,   96,  335,  101,
      100,  102,  105,  109,  113,  334,  106,  117,  103,  107,
      332,  110,  114,  111,  331,  115,   73,   73,  116,   73,
       73,  327,  112,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,  326,  118,  319,  122,  303,
      125,  143,  123,  119,  120,  279,   73,   73,  121,  129,

      247,   73,   73,  134,  204,  137,  126,  124,  136,  127,
      130,  131,  135,  132,  143,  133,   77,   77,   77,   77,
      140,  148,  148,  143,  140,   84,   73,   73,   84,  154,
       78,  143,   78,  156,  143,  149,  143,   84,  147,   82,
       84,   83,   83,  146,  150,  163,  150,  145,   84,  151,
      151,   83,   83,   73,   73,   85,  144,  153,  153,   82,
       84,  153,  153,  152,  141,   85,  140,   82,   84,   86,
       87,   88,   97,   97,  138,   88,   84,   73,   73,   91,
       84,   73,   73,   88,  155,   75,   98,   82,   84,  157,
      157,   73,   73,   73,   73,   74,  158,   73,   73,   73,

       73,   73,   73,  159,   73,   73,   73,   73,  158,  160,
       71,   73,   73,  161,  167,   70,  168,   73,   73,  347,
      162,   73,   73,   73,   73,  347,  164,   73,   73,  165,
      166,  170,  169,   73,   73,   73,   73,   73,   73,  347,
      171,   73,   73,   73,   73,   73,   73,   73,   73,  172,
       73,   73,  347,  175,  347,  173,  174,   73,   73,   73,
       73,  176,   73,   73,  177,   73,   73,  347,  178,   73,
       73,   73,   73,  347,  179,  180,   73,   73,  183,  181,
      182,  347,  186,   73,   73,   73,   73,  189,  185,  347,
      184,  347,  187,   73,   73,  178,   73,   73,  188,  347,

      192,   73,   73,   73,   73,   73,   73,   73,   73,  190,
      148,  148,  191,   73,   73,  139,  193,  151,  151,  195,
      199,  148,  148,  194,  149,  347,  197,  347,   84,  196,
      201,  152,  347,  202,  198,  149,  203,  347,  139,  200,
       84,   73,   73,  178,  347,  151,  151,  139,  151,  151,
       73,   73,   73,   73,   82,  139,  153,  153,  139,  152,
      139,  347,  152,   84,  206,   82,  347,  157,  157,  205,
       88,  150,  347,  150,  158,   84,  208,  208,  157,  157,
      347,  159,   73,   73,  347,  207,  158,   73,   73,  347,
      209,  347,  159,   73,   73,   73,   73,   73,   73,   73,

       73,   73,   73,   73,   73,  347,  211,   73,   73,  347,
      213,   73,   73,   73,   73,  210,  178,  347,  178,  212,
      214,   73,   73,   73,   73,   73,   73,  347,  218,   73,
       73,  347,  178,   73,   73,   73,   73,  219,  347,  215,
       73,   73,  220,  216,  217,   73,   73,  347,  221,  347,
      223,  347,  178,   73,   73,  224,  347,   73,   73,   73,
       73,   73,   73,   73,   73,  222,   73,   73,   73,   73,
       73,   73,   73,   73,  347,   73,   73,   73,   73,  347,
      228,  347,  178,  225,  178,  347,  226,   73,   73,  229,
       73,   73,  227,  347,  178,  230,   73,   73,  347,   73,

       73,   73,   73,  233,   73,   73,  347,  231,  232,   73,
       73,   73,   73,   73,   73,  347,   73,   73,   73,   73,
      238,  234,  237,  236,   73,   73,  240,  235,   73,   73,
       73,   73,   73,   73,   73,   73,  244,  239,  347,  245,
       73,   73,  241,  178,  242,   73,   73,  243,  347,  208,
      208,  208,  208,  248,   73,   73,  246,   73,   73,  250,
       73,   73,  249,  209,  347,  209,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,  251,   73,   73,  253,
       73,   73,  178,   73,   73,  252,   73,   73,  178,   73,
       73,   73,   73,   73,   73,  255,   73,   73,   73,   73,

      254,   73,   73,  178,  347,  259,  257,  347,  256,   73,
       73,  258,  261,  263,  347,  260,   73,   73,   73,   73,
       73,   73,   73,   73,  178,   73,   73,  262,   73,   73,
      347,  266,  264,  267,   73,   73,   73,   73,  347,  268,
       73,   73,   73,   73,  265,  269,   73,   73,   73,   73,
       73,   73,  347,  272,   73,   73,  270,  271,  347,  273,
      347,  178,   73,   73,   73,   73,   73,   73,  274,   73,
       73,  178,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,  276,  347,  275,  278,   73,   73,  280,   73,
       73,  283,  347,  281,  347,  284,  347,  277,   73,   73,

      347,  282,   73,   73,   73,   73,   73,   73,   73,   73,
      347,  178,   73,   73,   73,   73,  347,  285,   73,   73,
      347,  287,  288,  347,  286,   73,   73,   73,   73,   73,
       73,   73,   73,  347,  289,  347,   73,   73,  347,  290,
       73,   73,   73,   73,  347,  292,  291,  178,  178,   73,
       73,  347,  293,  295,   73,   73,  347,  296,   73,   73,
      294,   73,   73,   73,   73,  347,  298,   73,   73,  347,
      297,   73,   73,   73,   73,   73,   73,   73,   73,  305,
      178,   73,   73,   73,   73,   73,   73,  299,   73,   73,
      301,  347,  300,  347,  302,  178,   73,   73,   73,   73,

      306,   73,   73,   73,   73,  347,  304,   73,   73,  347,
       73,   73,  347,  307,  347,   73,   73,   73,   73,   73,
       73,  347,  308,   73,   73,  347,  310,  311,  347,  178,
      312,   73,   73,  178,   73,   73,  178,  347,  178,   73,
       73,  309,   73,   73,   73,   73,   73,   73,   73,   73,
      318,  347,   73,   73,   73,   73,  313,   73,   73,   73,
       73,  347,  314,   73,   73,  316,   73,   73,  347,   73,
       73,   73,   73,  315,  317,   73,   73,  347,  178,   73,
       73,  347,   73,   73,   73,   73,  347,  178,  321,  347,
      323,  347,  322,  347,  320,   73,   73,   73,   73,   73,

       73,   73,   73,   73,   73,  347,   73,   73,  347,  178,
      324,  347,  325,  347,  178,   73,   73,   73,   73,  347,
      178,  178,   73,   73,   73,   73,   73,   73,  329,  330,
      328,  347,   73,   73,  347,  347,  347,  347,  347,  347,
      347,  347,  178,  347,  347,  336,  347,  347,  178,  178,
      178,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  333,   58,   58,   58,   58,   63,   63,
       63,   63,   67,   67,   67,   67,  139,  347,  347,  139,
      142,  347,  142,  142,    9,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_chk[1146] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,  354,    3,    4,    4,  351,    4,    5,    5,
        6,    6,    7,    7,    8,    8,   24,    5,  344,    6,
       16,   16,   25,   25,   24,  343,    3,   26,   30,   30,
        4,   27,   26,   27,   27,   28,   25,   28,   28,  342,

       27,   32,   32,  341,   28,   33,   33,   27,   25,   34,
       34,   28,   27,   38,   38,  340,   28,  339,   39,   39,
       40,   40,   50,   50,   42,   42,  338,   38,   45,   45,
       41,   41,  337,   33,   39,   43,   43,   72,   72,   44,
       44,   50,   34,   42,  335,   41,  334,   34,  332,   40,
       39,   40,   41,   42,   44,  331,   41,   45,   40,   41,
      327,   43,   44,   43,  326,   44,   46,   46,   44,   47,
       47,  319,   43,   48,   48,   49,   49,   51,   51,   53,
       53,   52,   52,   54,   54,  318,   46,  305,   48,  279,
       49,   62,   48,   46,   46,  247,   94,   94,   47,   51,

      204,   96,   96,   52,  147,   54,   49,   48,   53,   49,
       51,   51,   52,   51,   62,   51,   78,   78,   77,   77,
      143,   82,   82,   62,  139,   77,  102,  102,   82,   94,
       78,   62,   77,   96,   62,   82,   62,   77,   79,   83,
       82,   83,   83,   69,   84,  102,   84,   66,   83,   84,
       84,   85,   85,   95,   95,   83,   65,   88,   88,   86,
       83,   86,   86,   84,   60,   85,   58,   87,   86,   87,
       87,   88,   98,   98,   56,   86,   87,   99,   99,   31,
       86,  100,  100,   87,   95,   22,   98,   97,   87,   97,
       97,  101,  101,  103,  103,   18,   97,  104,  104,  105,

      105,  106,  106,   97,  107,  107,  109,  109,   97,   99,
       14,  108,  108,  100,  105,   13,  106,  110,  110,    9,
      101,  111,  111,  112,  112,    0,  103,  113,  113,  104,
      104,  108,  107,  114,  114,  115,  115,  116,  116,    0,
      109,  117,  117,  118,  118,  119,  119,  120,  120,  110,
      121,  121,    0,  113,    0,  111,  112,  122,  122,  123,
      123,  114,  124,  124,  115,  125,  125,    0,  116,  126,
      126,  127,  127,    0,  117,  119,  128,  128,  121,  120,
      120,    0,  125,  129,  129,  130,  130,  127,  124,    0,
      122,    0,  126,  131,  131,  123,  132,  132,  126,    0,

      130,  133,  133,  134,  134,  135,  135,  136,  136,  128,
      149,  149,  129,  137,  137,  140,  130,  150,  150,  132,
      135,  148,  148,  131,  149,    0,  134,    0,  148,  133,
      136,  150,    0,  136,  134,  148,  137,    0,  140,  135,
      148,  155,  155,  135,    0,  151,  151,  140,  152,  152,
      154,  154,  156,  156,  153,  140,  153,  153,  140,  151,
      140,    0,  152,  153,  155,  157,    0,  157,  157,  154,
      153,  158,    0,  158,  157,  153,  158,  158,  159,  159,
        0,  157,  160,  160,    0,  156,  157,  161,  161,    0,
      158,    0,  159,  162,  162,  163,  163,  164,  164,  165,

      165,  167,  167,  166,  166,    0,  161,  168,  168,    0,
      163,  169,  169,  170,  170,  160,  164,    0,  165,  162,
      166,  171,  171,  172,  172,  173,  173,    0,  170,  174,
      174,    0,  167,  175,  175,  176,  176,  171,    0,  168,
      177,  177,  172,  169,  169,  178,  178,    0,  174,    0,
      176,    0,  173,  179,  179,  177,    0,  180,  180,  181,
      181,  182,  182,  183,  183,  175,  184,  184,  185,  185,
      186,  186,  187,  187,    0,  188,  188,  189,  189,    0,
      182,    0,  179,  180,  183,    0,  180,  190,  190,  184,
      192,  192,  181,    0,  185,  186,  191,  191,    0,  193,

      193,  194,  194,  189,  195,  195,    0,  187,  188,  196,
      196,  197,  197,  198,  198,    0,  199,  199,  201,  201,
      194,  190,  193,  192,  202,  202,  196,  191,  200,  200,
      203,  203,  205,  205,  206,  206,  201,  195,    0,  202,
      207,  207,  198,  197,  199,  210,  210,  200,    0,  208,
      208,  209,  209,  205,  211,  211,  203,  213,  213,  207,
      212,  212,  206,  208,    0,  209,  214,  214,  215,  215,
      216,  216,  217,  217,  218,  218,  210,  220,  220,  212,
      219,  219,  213,  221,  221,  211,  222,  222,  214,  223,
      223,  224,  224,  225,  225,  217,  226,  226,  227,  227,

      215,  228,  228,  216,    0,  222,  219,    0,  218,  229,
      229,  221,  225,  227,    0,  223,  230,  230,  231,  231,
      232,  232,  233,  233,  224,  234,  234,  226,  235,  235,
        0,  230,  228,  231,  236,  236,  237,  237,    0,  232,
      238,  238,  239,  239,  229,  233,  240,  240,  241,  241,
      242,  242,    0,  237,  243,  243,  234,  236,    0,  239,
        0,  235,  244,  244,  245,  245,  246,  246,  240,  248,
      248,  238,  249,  249,  250,  250,  251,  251,  252,  252,
      253,  253,  242,    0,  241,  246,  254,  254,  248,  255,
      255,  251,    0,  249,    0,  253,    0,  245,  256,  256,

        0,  250,  257,  257,  258,  258,  259,  259,  260,  260,
        0,  252,  261,  261,  262,  262,    0,  255,  263,  263,
        0,  257,  258,    0,  256,  264,  264,  267,  267,  265,
      265,  266,  266,    0,  260,    0,  268,  268,    0,  261,
      269,  269,  270,  270,    0,  264,  263,  262,  265,  271,
      271,    0,  266,  268,  272,  272,    0,  269,  273,  273,
      267,  274,  274,  275,  275,    0,  271,  276,  276,    0,
      270,  277,  277,  278,  278,  280,  280,  281,  281,  282,
      273,  282,  282,  283,  283,  284,  284,  272,  285,  285,
      276,    0,  274,    0,  277,  275,  286,  286,  287,  287,

      283,  288,  288,  289,  289,    0,  280,  290,  290,    0,
      291,  291,    0,  284,    0,  292,  292,  293,  293,  294,
      294,    0,  285,  295,  295,    0,  290,  291,    0,  286,
      292,  296,  296,  288,  297,  297,  293,    0,  294,  298,
      298,  289,  299,  299,  300,  300,  301,  301,  302,  302,
      304,    0,  304,  304,  306,  306,  295,  307,  307,  308,
      308,    0,  299,  309,  309,  301,  310,  310,    0,  311,
      311,  313,  313,  300,  302,  312,  312,    0,  308,  314,
      314,    0,  315,  315,  316,  316,    0,  306,  311,    0,
      313,    0,  312,    0,  310,  317,  317,  320,  320,  321,

      321,  322,  322,  323,  323,    0,  324,  324,    0,  314,
      315,    0,  316,    0,  317,  325,  325,  328,  328,    0,
      322,  323,  329,  329,  330,  330,  333,  333,  321,  324,
      320,    0,  336,  336,    0,    0,    0,    0,    0,    0,
        0,    0,  329,    0,    0,  333,    0,    0,  325,  328,
      336,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  330,  348,  348,  348,  348,  349,  349,
      349,  349,  350,  350,  350,  350,  352,    0,    0,  352,
      353,    0,  353,  353,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
//Cesário Ribeiro da Fonseca Andrade Silva - 2015230724
//Pedro Carreiro Carvalho - 2017267408

#include <stdio.h>
#include <string.h>
#include "y.tab.h"
#define LINHA linha++; coluna=1;
#define COLUNA coluna+=yyleng;

int flag = 0, flagAux=0;
int linha = 1;
int coluna = 1;
int c_actual=1;
int l_actual=1;
int error=0;
char save[256];

#line 827 "lex.yy.c"

#line 829 "lex.yy.c"

#define INITIAL 0
#define STRINGLIT 1
#define ML_COMMENT 2
#define OL_COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 45 "jucompiler.l"


#line 1052 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1085 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", linha, coluna, yytext);COLUNA;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{BEGIN OL_COMMENT;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 50 "jucompiler.l"
{LINHA;BEGIN 0;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{COLUNA;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{c_actual = coluna; l_actual = linha;COLUNA;BEGIN(ML_COMMENT);}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 54 "jucompiler.l"
{LINHA;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{COLUNA;}
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 56 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", l_actual, c_actual); return 0;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{COLUNA;BEGIN 0;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if(flag==-1)printf("RESERVED(%s)\n", yytext);COLUNA;if(flagAux==1){return RESERVED;}}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{if(flag==-1)printf("RESERVED(%s)\n", yytext); COLUNA;if(flagAux==1){return UNARY;}}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if(flag==-1)printf("BOOLLIT(false)\n");COLUNA;if(flagAux==1){return BOOLLIT;}}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if(flag==-1)printf("BOOLLIT(true)\n");COLUNA;if(flagAux==1){return BOOLLIT;}}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if(flag==-1)printf("AND\n");COLUNA; if(flagAux==1){return AND;}}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if(flag==-1)printf("ASSIGN\n");COLUNA;if(flagAux==1){return ASSIGN;}}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if(flag==-1)printf("STAR\n");COLUNA;if(flagAux==1){return STAR;}}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if(flag==-1)printf("DIV\n");COLUNA;if(flagAux==1){return DIV;}}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(flag==-1)printf("COMMA\n");COLUNA;if(flagAux==1){return COMMA;}}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if(flag==-1)printf("EQ\n");COLUNA;if(flagAux==1){return EQ;}}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if(flag==-1)printf("GT\n");COLUNA;if(flagAux==1){return GT;}}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{if(flag==-1)printf("GE\n");COLUNA;if(flagAux==1){return GE;}}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if(flag==-1)printf("LBRACE\n");COLUNA;if(flagAux==1){return LBRACE;}}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if(flag==-1)printf("LE\n");COLUNA;if(flagAux==1){return LE;}}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if(flag==-1)printf("LPAR\n");COLUNA;if(flagAux==1){return LPAR;}}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if(flag==-1)printf("LSQ\n");COLUNA;if(flagAux==1){return LSQ;}}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if(flag==-1)printf("LT\n");COLUNA;if(flagAux==1){return LT;}}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if(flag==-1)printf("MINUS\n");COLUNA;if(flagAux==1){return MINUS;}}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if(flag==-1)printf("MOD\n");COLUNA;if(flagAux==1){return MOD;}}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if(flag==-1)printf("NE\n");COLUNA;if(flagAux==1){return NE;}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if(flag==-1)printf("NOT\n");COLUNA;if(flagAux==1){return NOT;}}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if(flag==-1)printf("OR\n");COLUNA;if(flagAux==1){return OR;}}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if(flag==-1)printf("PLUS\n");COLUNA;if(flagAux==1){return PLUS;}}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if(flag==-1)printf("RBRACE\n");COLUNA;if(flagAux==1){return RBRACE;}}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if(flag==-1)printf("RPAR\n");COLUNA;if(flagAux==1){return RPAR;}}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if(flag==-1)printf("RSQ\n");COLUNA;if(flagAux==1){return RSQ;}}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if(flag==-1)printf("SEMICOLON\n");COLUNA;if(flagAux==1){return SEMICOLON;}}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if(flag==-1)printf("ARROW\n");COLUNA;if(flagAux==1){return ARROW;}}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if(flag==-1)printf("LSHIFT\n");COLUNA;if(flagAux==1){return LSHIFT;}}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if(flag==-1)printf("RSHIFT\n");COLUNA;if(flagAux==1){return RSHIFT;}}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if(flag==-1)printf("XOR\n");COLUNA;if(flagAux==1){return XOR;}}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if(flag==-1)printf("BOOL\n");COLUNA;if(flagAux==1){return BOOL;}}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if(flag==-1)printf("CLASS\n");COLUNA;if(flagAux==1){return CLASS;}}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if(flag==-1)printf("DOTLENGTH\n");COLUNA;if(flagAux==1){return DOTLENGHT;}}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if(flag==-1)printf("DOUBLE\n");COLUNA;if(flagAux==1){return DOUBLE;}}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if(flag==-1)printf("ELSE\n");COLUNA;if(flagAux==1){return ELSE;}}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if(flag==-1)printf("IF\n");COLUNA;if(flagAux==1){return IF;}}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if(flag==-1)printf("INT\n");COLUNA;if(flagAux==1){return INT;}}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if(flag==-1)printf("PRINT\n");COLUNA;if(flagAux==1){return PRINT;}}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if(flag==-1)printf("PARSEINT\n");COLUNA;if(flagAux==1){return PARSEINT;}}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if(flag==-1)printf("PUBLIC\n");COLUNA;if(flagAux==1){return PUBLIC;}}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{if(flag==-1)printf("STATIC\n");COLUNA;if(flagAux==1){return STATIC;}}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{if(flag==-1)printf("STRING\n");COLUNA;if(flagAux==1){return STRING;}}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{if(flag==-1)printf("VOID\n");COLUNA;if(flagAux==1){return VOID;}}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{if(flag==-1)printf("WHILE\n");COLUNA;if(flagAux==1){return WHILE;}}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{if(flag==-1)printf("RETURN\n");COLUNA;if(flagAux==1){return RETURN;}}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{BEGIN STRINGLIT; strcat(save, yytext); l_actual= linha; c_actual= coluna;COLUNA; error=0;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{COLUNA; strcat(save, yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n", linha, coluna, yytext);COLUNA;error=1;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{BEGIN 0; strcat(save, yytext); if(error==0){if(flag==-1)printf("STRLIT(%s)\n",save);} COLUNA;if(flagAux==1 && error == 0){yytext=strdup(save);save[0]=0;return STRLIT;};save[0]=0;}
	YY_BREAK
case YY_STATE_EOF(STRINGLIT):
#line 110 "jucompiler.l"
{BEGIN 0; save[0]=0;printf("Line %d, col %d: unterminated string literal\n", l_actual, c_actual);LINHA;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 111 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n", linha, c_actual);LINHA;BEGIN 0; save[0]=0;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{COLUNA;}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 114 "jucompiler.l"
{LINHA;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if(flag==-1)printf("INTLIT(0)\n");COLUNA;if(flagAux==1){return INTLIT;}}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{if(flag==-1)printf("INTLIT(%s)\n", yytext);COLUNA;if(flagAux==1){return INTLIT;}}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if(flag==-1)printf("REALLIT(%s)\n", yytext);COLUNA;if(flagAux==1){return REALLIT;}}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if(flag==-1)printf("REALLIT(%s)\n", yytext);COLUNA;if(flagAux==1){return REALLIT;}}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{if(flag==-1)printf("REALLIT(%s)\n", yytext);COLUNA;if(flagAux==1){return REALLIT;}}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{if(flag==-1)printf("INTLIT(%s)\n", yytext);COLUNA;if(flagAux==1){return INTLIT;}}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "jucompiler.l"
{if(flag==-1)printf("ID(%s)\n", yytext);COLUNA;if(flagAux==1){return ID;}}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 125 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", linha, coluna, yytext);COLUNA;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 127 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1471 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(OL_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 347);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 127 "jucompiler.l"


int main(int argc, char *argv[]){
    
    if(argc > 1){

        if(strcmp(argv[1],"-l") == 0){
            flag = - 1;
        }

        if(strcmp(argv[1],"-e1") == 0){
            flag = 1;
        }

        if(strcmp(argv[1],"-e2") == 0){
            flag = 1;
            flagAux=1;
        }
    }


    
    if(flagAux==0){
        yylex();
    }else{
        yyparse();
    }
    return 0;
}

int yywrap(){
    return 1;
}
